notifications:
  email:
    recipients:
      - onurrozkaan@gmail.com

    # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always

# specify language
language: node_js

# configure which branches to run
branches:
  # whitelist
  only:
    - master
  # blacklist
  except:
    - test
